baseURL = "https://samuelwflint.com/"
languageCode = "en-us"
title = "Samuel W. Flint"
theme = ["hugo-kiera", "matomo", "bibliography"]
enableRobotsTXT = "true"
disqusShortname = "samflint-com"
copyright = "&copy; Samuel Flint"
enableGitInfo = "true"

[permalinks]
    posts = "/posts/:year/:month/:day/:title/"
    pages = "/pages/:title"

[params]
    tagline = "A tech and academic blog"
    show_comments = "true"
    commentAutoload = "true"
    favicon = "/favicon.ico"
    mathjax = true

[author]
    name = "Samuel W. Flint"
    email = "swflint(at)flintfam(dot)org"
    github = "swflint"
    stackoverflow = "u/2378492"
    linkedin = "swflint"
    twitter = "SamuelWFlint"
    mastodon = "mstdn.io/@swflint"
    orcid = "0000-0002-8023-9710"

[params.matomo]
   url = "https://stats.flintfam.org"
   id = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/pages/about/"
    weight = 1

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/pages/publications/"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/pages/projects/"
    weight = 3

[[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages/"
    weight = 4

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 5

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6
