baseURL = "http://samflint.com/"
languageCode = "en-us"
title = "Samuel W. Flint"
theme = "hugo-kiera"

[params]
    #tagline = "the tagline for this website"

[author]
    name = "Samuel W. Flint"           #Author name
    github = "swflint"         #Github username
    #gitlab = ""         #Gitlab username
    #linkedin = ""       #LinkedIn username
    #facebook = ""       #Facebook username
    twitter = "SamuelWFlint"        #Twitter username
    #instagram = ""      #Instagram username
    stackoverflow = ""  #StackOverflow username

[[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
