baseURL = "https://samuelwflint.com/"
languageCode = "en-us"
theme = ["anatole", "bibliography"]
enableRobotsTXT = "true"
enableGitInfo = "true"

[permalinks]
    posts = "/posts/:year/:month/:day/:title/"
    pages = "/pages/:title"

[params]
    tagline = "A tech and academic blog"
    favicon = "/favicon.ico"
    title = "Samuel W. Flint"
    author = "Samuel W. Flint"
    copyright = "Placed under a CC-0 license"
    profilePicture = "/img/headshot-2021-cropped.png"
    disableThemeSwitcher = true
    doNotLoadAnimations = true
    contentRatio = 0.7
    mainSections = []

[params.math]
    enable = true
    use = "katex"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "email"
url = "mailto:swflint(at)flintfam(dot)org"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/swflint"

[[params.socialIcons]]
icon = "fab fa-stack-overflow"
title = "StackOverflow"
url = "https://stackoverflow.com/u/2378492"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/swflint"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/SamuelWFlint"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCiD"
url = "https://orcid.org/0000-0002-8023-9710"

[[params.socialIcons]]
icon = "fas fa-key"
title = "PGP Key"
url = "/pages/pgp/"

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/pages/publications/"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/pages/projects/"
    weight = 3

[[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages/"
    weight = 4

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 5

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6
