baseURL = "http://samflint.com/"
languageCode = "en-us"
title = "Samuel W. Flint"
theme = "hugo-kiera"
tagline = ""
enableRobotsTXT = "true"

[params]
    #tagline = "the tagline for this website"

[author]
    name = "Samuel W. Flint"           #Author name
    github = "swflint"         #Github username
    linkedin = "swflint"       #LinkedIn username
    twitter = "SamuelWFlint"        #Twitter username
    mastodon = "mstdn.io/@swflint"
    stackoverflow = "u/2378492"  #StackOverflow username
    orcid = "0000-0002-8023-9710"

[[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"

[[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages/"

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/RSS"
  baseName = "feed"
