baseURL = "http://samflint.com/"
languageCode = "en-us"
title = "Samuel W. Flint"
theme = "hugo-kiera"
enableRobotsTXT = "true"
disqusShortname = "samflint-com"
copyright = "&copy; Samuel Flint"

[permalinks]
    posts = "/:year/:month/:title/"
    pages = "/pages/:title"

[params]
    tagline = "A tech and academic blog"
    show_comments = "true"
    commentAutoload = "true"
    favicon = "favicon.ico"

[author]
    name = "Samuel W. Flint"
    email = "swflint(at)flintfam(dot)org"
    github = "swflint"
    stackoverflow = "u/2378492"
    linkedin = "swflint"
    twitter = "SamuelWFlint"
    mastodon = "mstdn.io/@swflint"
    orcid = "0000-0002-8023-9710"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/pages/about/"

[[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"

[[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages/"

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
