baseURL = "http://samflint.com/"
languageCode = "en-us"
title = "Samuel W. Flint"
theme = "hugo-kiera"
tagline = ""
enableRobotsTXT = "true"
disqusShortname = "samflint-com"
CommentAutoload = "true"

[params]
    #tagline = "the tagline for this website"

[author]
    name = "Samuel W. Flint"
    email = "swflint(at)flintfam(dot)org"
    github = "swflint"
    stackoverflow = "u/2378492"
    linkedin = "swflint"
    twitter = "SamuelWFlint"
    mastodon = "mstdn.io/@swflint"
    orcid = "0000-0002-8023-9710"

[[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"

[[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages/"

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/RSS"
  baseName = "feed"
