---
title: "Emacs Killer App"
date: 2014-01-12T08:58:00-05:00
draft: false
---

* Intro

Why do I use Emacs, well, for a few reasons, but mostly these major-modes:
 - Org Mode
 - AucTeX
 - GNUS
These are Emacs' killer apps, they make life *so* much easier.

* Org Mode

OrgMode is awesome!  It's like an outliner, agenda, personal organizer and wiki, all rolled into one!

I use Org mode for just about everything.  It's my organizer, todo list, notes wiki, and library management system.  I even wrote this post with Org Mode.

An example Org-mode document might look something like this:
#+CAPTION: Example Org Document
#+Name: example-org-document
#+BEGIN_SRC org
  ,#+Title: Sample OrgMode Document
  ,#+Author: Sam Flint

  ,* First Level headline
  ,** Second level headline
    ,*Emphasized Text*
   - bulleted
   - list

#+END_SRC

Now of course this doesn't even scratch the surface!

I regularly use Org Mode to do Literate programming even.

* AucTeX

I regularly use LaTeX to do my documents, and the built in Emacs LaTeX mode is ok, but AucTeX is just divine.  It has completion, built in document parsing, preview and so much more.

* GNUS

Yes, this means I check my email in emacs, but it integrates with OrgMode so well.
