---
title: "Wonders of Org Mode"
date: 2013-10-04T16:20:00-05:00
draft: false
---

* Intro

Org-mode is a wonderful tool, it allows you to do just about anything!

You can:
 - keep a schudule
 - implement GTD
 - capture notes and the like
 - keep interlinked files and notes
 - produce reproducible research
 - program with LP techniques
 - and more

* Schedule

Org mode can be your schedule!  Heck, I use it as my schedule.

It's quite simple, just create your headline with a timestamp.  The timestamp format is something like:

#+BEGIN_SRC org
  <2013-10-04 Fri 12:00-13:30>
#+END_SRC

Scheduling can even include repeaters or ranges, both simple and complex.

* GTD

I don't use GTD methods, but I hear you can implement GTD with Org, see this [[http://members.optusnet.com.au/~charles57/GTD/orgmode.html][article]].

* Capture

Org-capture allows you to capture notes, thoughts, and other things with the same outline structure, in your files.

* Interlinked Notes

This is one of the best parts!  Org-mode is like a wiki, but there is only one author.  With org being like a wiki, one can link notes, ideas, thoughts, schedule entries, and the like, creating an excellent exocortex.

* Reproducible Research

See LP.

* LP

Literate programming!  Woo!

Org allows you to produce literate programming documents, which means you can easily interweave your code and your documentation.
