---
title: "How I Work (Updated)"
date: 2020-06-27T13:19:57-05:00
draft: true
tags: ['emacs', 'org-mode' , 'productivity']
---

Academics or not, nerds love to talk about how they work, and what tools they use.  I've written about it [[{{< ref "posts/2017/how-i-work/index.org" >}}][before]], but I'd like to clean it up, and discuss how things have changed, kinda.  I'll talk about the "big four", /i.e./, software, hardware, physical environment and methods.

* Methods

* Software

* Hardware

** Computers

 - Laptop: Lenovo Yoga 11e.  It's a small, easily packable laptop with a suprisingly comfortable keyboard (as well as a touch screen and "convertible" functionality that I never use).
 - Desktop: Lenovo ThinkCentre M720q in a Tiny-in-One third-generation 22-inch monitor.

** Peripherals

 - The Keyboard: Kinesis Advantage2 (software layout Programmer's Dvorak, Caps Lock is Backspace).  This keyboard is amazing --- it fits my hands, the key switches are perfect, and the key-stroke programmability mean that I can change keys quickly and easily, which moved some modifiers around to a more convenient location (as well as doubled others).
 - The Trackball: Because of some RSI scares (and because it freaks people out), I use a Trackball, namely the Elecom EX-G.  It's Japanese, has a total of ten buttons, and fits my hand fairly well.
 - The Printer: I prefer to edit & read on paper, as well as have frequent need to scan documents.  I use a Brother MFC L2707-DW, which works quite well to print at speed, and produces excellent output.

** Non-Computer Electronics

 - Cell Phone: A generic Android phone, nothing special.  I do use a non-standard home screen, Nova Launcher, however things are otherwise pretty vanilla.
 - Desk Phone: Western Electric 2500 on AxVoice.  Yes, I still use an old-school phone, in part because it's easier to shoulder so I can do things while talking to someone.
 - External Cryptographic Hardware: NitroKey Pro.  My GPG Key is kept on one of these, and they're great little devices, I only wish they came in a retractable version.
 - Fitness Tracker: Whoop Band 3.0.  For hardware that requires a paid service it's great.
 - Earbuds & Headphones: Trekz Air & Soundcore Spirit Pro.

* Physical Environment & Accessories

** Daily Carry

 - Timbuk2 Command Messenger Bag, Medium -- This messenger bag is great.  It fits my laptop, a notepad, a couple of textbooks, and most of the other things I need.
 - Camino Folding Bookstand for when I'm seriously studying -- it keeps books open to the right page and held at the right angle to make note taking easier.
 - HDMI to VGA adapter
 - Logitech Slideshow Remote
 - Pickett N 200-T Trig Slide Rule
 - USB-C Cable
 - Tide Pen
 - Fisherman's Friend for when my throat gets dry or irritated (thanks allergies!)

** Desk and Note Taking

 - Desk: Standing Desk, 5.5' x 2.5'.  Built using a Vivo base, plywood top with laminate.  There's an Amazon Basics laptop stand and a daylight lamp sitting on it, as well as my desktop and phone.  I also have a USB peripheral switcher to switch my keyboard and mouse between the two computers.
 - Paper: Mostly cheap legal pads and a Swingline from the 60s.
 - The Pens:  Fountain pens of various kinds, mostly inked with Diamine Oxford Blue, including:
   - Parker 21 Desk Set
   - 2 Lamy Safaris
   - Noodler's Boston Safety Pen
   - Esterbrook "J"
   - Black Kaweco Perkeo

** Coffee

Lots of it, Chemex, fresh ground, local beans.

