---
title: "About"
date: 2020-06-25T10:45:47-05:00
lastmod: 2020-06-26T20:22:08-05:00
draft: false
disableComments: "true"
---

My name is Sam Flint.  I'm currently a PhD student at the University of Nebraska---Lincoln studying Computer Science.  I completed my BS in the same at the same in 2020.  My background is in fundamentals and classical AI, but I'm currently studying Machine Learning and related techniques, and am interested in effective undergraduate Computer Science education.

Outside of the academic, I'm a firm supporter of Free Software, and contribute to several projects, as well as maintain some of my own (see [[{{< ref "pages/projects/index.org">}}][here]]), and am an ardent Emacs user.  My other hobbies include cooking, baking, antique collecting and as of late, bicycling.

* PGP

I'm an avid user of PGP, and enjoy the benefits of its use for message security and maintenance of privacy.  If you are capable of doing so, please sign your messages or even encrypt them.  My key is available on ~hkp://pool.sks-keyservers.net~, my key ID is ~FA13D704~ (also available [[file:/attach/FA13D704.asc][here]]).

Watch here for notification of Key Revocation.  The following keys have been revoked:

 - 266596F4 revoked and superceded by 2E2B259F.  Statement is [[file:/attach/rev-sup-266596F4.txt][here]].
 - 2E2B259F revoked and superceded by FA13D704.  Statement is [[file:/attach/rev-sup-2E2B259F.txt][here]].
